package mybatis.models;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.id
     *
     * @mbg.generated Tue May 03 11:18:31 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.name
     *
     * @mbg.generated Tue May 03 11:18:31 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.id
     *
     * @return the value of USERS.id
     *
     * @mbg.generated Tue May 03 11:18:31 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.id
     *
     * @param id the value for USERS.id
     *
     * @mbg.generated Tue May 03 11:18:31 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.name
     *
     * @return the value of USERS.name
     *
     * @mbg.generated Tue May 03 11:18:31 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.name
     *
     * @param name the value for USERS.name
     *
     * @mbg.generated Tue May 03 11:18:31 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}